/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ph.edu.slu.weavingpayrollapp.ui;

/**
 *
 * @author angelrosemilo
 */
public class Payroll extends javax.swing.JFrame {

    /**
     * Creates new form Payroll
     */
    public Payroll() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                { new Integer(10111), "Locaben, Camille", "General Manager",  new Double(1200.0),  new Double(31200.0),  new Double(26.0),  new Double(31200.0),  new Double(581.3),  new Integer(100),  new Double(337.5),  new Double(5058.64),  new Double(25587.69)},
                { new Integer(10211), "Balilit,Marian T.", "Head Supervisor",  new Double(900.0),  new Double(23400.0),  new Double(26.0),  new Double(23400.0),  new Double(581.3),  new Integer(100),  new Double(337.5),  new Double(5058.64),  new Double(25587.69)},
                { new Integer(10212), "Lucahi,Preciouslyn B.", "Head Supervisor",  new Double(900.0),  new Double(23400.0),  new Double(26.0),  new Double(23400.0),  new Double(581.3),  new Integer(100),  new Double(337.5),  new Double(5058.64),  new Double(25587.69)},
                { new Integer(10213), "Sacedon, Mary Jhoe M.", "Accountant",  new Double(700.0),  new Double(18200.0),  new Double(26.0),  new Double(18200.0),  new Double(581.3),  new Integer(100),  new Double(337.5),  new Double(5058.64),  new Double(25587.69)},
                { new Integer(10214), "Dirige, Renzo Lanz O.", "Acountant",  new Double(700.0),  new Double(18200.0),  new Double(26.0),  new Double(18200.0),  new Double(581.3),  new Integer(100),  new Double(337.5),  new Double(5058.64),  new Double(25587.69)},
                { new Integer(10215), "avelino,michelle f", "Clerk",  new Double(400.0),  new Double(10400.0),  new Double(26.0),  new Double(10400.0),  new Double(581.3),  new Integer(100),  new Double(337.5),  new Double(5058.64),  new Double(25587.69)},
                { new Integer(10216), "Uy, John Michael V", "Clerk",  new Double(400.0),  new Double(10400.0),  new Double(26.0),  new Double(400.0),  new Double(581.3),  new Integer(100),  new Double(337.5),  new Double(5058.64),  new Double(25587.69)},
                { new Integer(10217), "PABITO, Haydee Mae B.", "Clerk",  new Double(400.0),  new Double(10400.0),  new Double(26.0),  new Double(10400.0),  new Double(581.3),  new Integer(100),  new Double(337.5),  new Double(5058.64),  new Double(25587.69)},
                { new Integer(10311), "Reyes, Judylyn U.", "Production Supervisor",  new Double(400.0),  new Double(10400.0),  new Double(26.0),  new Double(10400.0),  new Double(581.3),  new Integer(100),  new Double(337.5),  new Double(5058.64),  new Double(25587.69)},
                { new Integer(10312), "LANDAGORA, MARK ANDY B. ", "Production Supervisor",  new Double(400.0),  new Double(10400.0),  new Double(26.0),  new Double(10400.0),  new Double(581.3),  new Integer(100),  new Double(337.5),  new Double(5058.64),  new Double(25587.69)},
                { new Integer(10411), "Dirige, Renzo Lanz O.", "Production Operator",  new Double(320.0),  new Double(8320.0),  new Double(26.0),  new Double(8320.0),  new Double(581.3),  new Integer(100),  new Double(337.5),  new Double(5058.64),  new Double(25587.69)},
                { new Integer(10412), "LUMIUAN, RHEA B.", "Production Operator",  new Double(320.0),  new Double(8320.0),  new Double(26.0),  new Double(8320.0),  new Double(581.3),  new Integer(100),  new Double(337.5),  new Double(5058.64), null},
                { new Integer(10413), null, "Production Operator", null, null, null, null, null, null, null, null, null},
                { new Integer(10414), null, "Production Operator", null, null, null, null, null, null, null, null, null},
                { new Integer(10415), null, "Production Operator", null, null, null, null, null, null, null, null, null},
                { new Integer(10416), null, "Production Operator", null, null, null, null, null, null, null, null, null},
                { new Integer(10417), null, "Production Operator", null, null, null, null, null, null, null, null, null},
                { new Integer(10418), null, "Production Operator", null, null, null, null, null, null, null, null, null},
                { new Integer(10421), null, "Tailor", null, null, null, null, null, null, null, null, null},
                { new Integer(10422), null, "Tailor", null, null, null, null, null, null, null, null, null},
                { new Integer(10423), null, "Tailor", null, null, null, null, null, null, null, null, null},
                { new Integer(10424), null, "Tailor", null, null, null, null, null, null, null, null, null},
                { new Integer(10425), null, "Tailor", null, null, null, null, null, null, null, null, null},
                { new Integer(10426), null, "Tailor", null, null, null, null, null, null, null, null, null},
                { new Integer(10427), null, "Tailor", null, null, null, null, null, null, null, null, null},
                { new Integer(10428), null, "Tailor", null, null, null, null, null, null, null, null, null},
                { new Integer(10511), null, "Maintenance Man", null, null, null, null, null, null, null, null, null},
                { new Integer(10512), null, "Machine Maintenance Man", null, null, null, null, null, null, null, null, null},
                { new Integer(10513), null, "Machine Maintenance Man", null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Employee Name", "Company Position", "Rate Per Day", "Basic Monthly Rate", "Days Worked", "Basic Monthly Pay", "SSS Contribution", "PAG-IBIG Contribution", "PHIL- HEALTH Contribution", "TOTAL Deduction", "NET PAY"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("PAYROLL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(611, 611, 611)
                .addComponent(jLabel1)
                .addContainerGap(602, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payroll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
